version: "3.8"

networks:
    laravel:

services:
  php:
    build: docker/php
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
        - laravel
  nginx:
    build: docker/nginx
    volumes:
        - .:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - php
    networks:
        - laravel
  db:
    image: "postgres:14"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
        - laravel

  db_test:
    env_file: .env.testing
    image: "postgres:14"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data_test
    ports:
      - "5433:5432"
    networks:
        - laravel

volumes:
  db_data:
